// Copyright (c) 2026 Mauro Silva. All rights reserved.
// SPDX-License-Identifier: LicenseRef-Proprietary

package main

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/hoplock/proxy/internal/sshtest"
	"golang.org/x/crypto/ssh"
)

// proxyProcess is the real hoplock-proxy binary, run as a child process.
//
// In-process would have been less code, and would have made every memory
// number meaningless: RSS is per process, and a harness that shares a heap with
// the thing it is measuring cannot say what a live connection costs. Running the
// shipped binary also means the run exercises the real startup path — config
// decoding, the revocation subscription, the logging pipeline — rather than a
// convenient subset of it.
type proxyProcess struct {
	binary  string
	addr    string
	hostKey ssh.PublicKey

	cmd  *exec.Cmd
	logs *strings.Builder
	mu   sync.Mutex
}

// proxySetup is what the harness must generate before the proxy can start.
type proxySetup struct {
	Dir        string
	ControlURL string
	Token      string
	ProxyID    string
	ListenAddr string
	Scenario   *Scenario
}

// startProxy writes the material and config for a run, launches the binary, and
// waits for its listener to accept.
func startProxy(ctx context.Context, binary string, s proxySetup) (*proxyProcess, error) {
	hostSigner, hostKeyPEM, err := sshtest.GenerateKeyPair()
	if err != nil {
		return nil, err
	}
	_, targetKeyPEM, err := sshtest.GenerateKeyPair()
	if err != nil {
		return nil, err
	}

	hostKeyPath := filepath.Join(s.Dir, "host_key")
	targetKeyPath := filepath.Join(s.Dir, "target_key")
	bufferDir := filepath.Join(s.Dir, "logbuf")
	if err := os.WriteFile(hostKeyPath, hostKeyPEM, 0o600); err != nil {
		return nil, err
	}
	if err := os.WriteFile(targetKeyPath, targetKeyPEM, 0o600); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(bufferDir, 0o700); err != nil {
		return nil, err
	}

	cfg := renderProxyConfig(s, hostKeyPath, targetKeyPath, bufferDir)
	cfgPath := filepath.Join(s.Dir, "config.yaml")
	if err := os.WriteFile(cfgPath, []byte(cfg), 0o600); err != nil {
		return nil, err
	}

	p := &proxyProcess{
		binary:  binary,
		addr:    s.ListenAddr,
		hostKey: hostSigner.PublicKey(),
		logs:    &strings.Builder{},
	}

	cmd := exec.CommandContext(ctx, binary, "-config", cfgPath)
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return nil, err
	}
	cmd.Stdout = io.Discard
	if err := cmd.Start(); err != nil {
		return nil, fmt.Errorf("start proxy %s: %w", binary, err)
	}
	p.cmd = cmd
	go p.drain(stderr)

	if err := waitListening(p.addr, 20*time.Second); err != nil {
		_ = p.stop()
		return nil, fmt.Errorf("%w\nproxy log:\n%s", err, p.log())
	}
	return p, nil
}

// drain keeps the proxy's stderr so a failed run can print it. It is bounded:
// a run that logs a million lines must not be diagnosed by exhausting memory.
func (p *proxyProcess) drain(r io.Reader) {
	const maxLog = 64 << 10
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 8192), 1<<20)
	for sc.Scan() {
		p.mu.Lock()
		if p.logs.Len() < maxLog {
			p.logs.WriteString(sc.Text())
			p.logs.WriteByte('\n')
		}
		p.mu.Unlock()
	}
}

func (p *proxyProcess) log() string {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.logs.String()
}

func (p *proxyProcess) pid() int { return p.cmd.Process.Pid }

func (p *proxyProcess) stop() error {
	if p.cmd == nil || p.cmd.Process == nil {
		return nil
	}
	_ = p.cmd.Process.Signal(os.Interrupt)
	done := make(chan error, 1)
	go func() { done <- p.cmd.Wait() }()
	select {
	case <-done:
	case <-time.After(5 * time.Second):
		_ = p.cmd.Process.Kill()
		<-done
	}
	return nil
}

func waitListening(addr string, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp", addr, time.Second)
		if err == nil {
			_ = conn.Close()
			return nil
		}
		time.Sleep(50 * time.Millisecond)
	}
	return errors.New("proxy did not start listening on " + addr)
}

// renderProxyConfig writes the bootstrap config for a run. It is written out in
// full rather than patched from config.example.yaml so the report can print
// exactly what the measured proxy was configured with.
func renderProxyConfig(s proxySetup, hostKeyPath, targetKeyPath, bufferDir string) string {
	sc := s.Scenario
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by cmd/loadgen for scenario %q — do not edit\n", sc.Name)
	fmt.Fprintf(&b, "proxy:\n  id: %q\n  listen_addr: %q\n  host_key_path: %q\n",
		s.ProxyID, s.ListenAddr, hostKeyPath)
	fmt.Fprintf(&b, "control:\n  base_url: %q\n  token: %q\n  cache:\n    max_ttl: %s\n    stale_after: %s\n",
		s.ControlURL, s.Token, sc.Proxy.CacheMaxTTL, sc.Proxy.CacheStaleAfter)
	fmt.Fprintf(&b, "dial:\n  dial_timeout: 15s\n  default_target_port: 22\n")
	fmt.Fprintf(&b, "logging:\n  buffer_dir: %q\n  batch_size: %d\n  flush_interval: %s\n"+
		"  queue_size: %d\n  send_timeout: 10s\n  retry_min: 1s\n  retry_max: 10s\n  max_payload_bytes: 32768\n",
		bufferDir, sc.Proxy.LogBatchSize, sc.Proxy.LogFlushInterval, sc.Proxy.LogQueueSize)
	fmt.Fprintf(&b, "routing:\n  target_delimiter: \"#\"\n")
	fmt.Fprintf(&b, "auth:\n  user:\n    methods: [\"cert\"]\n")
	// static-key on purpose: it provisions nothing, so establishment cost is
	// not confounded by a credential method. Provisioning is measured on its
	// own, in the provisioning kind, because it saturates a target rather than
	// a proxy.
	fmt.Fprintf(&b, "  target:\n    method: \"static-key\"\n    static_key:\n      key_path: %q\n      username: \"loadgen\"\n",
		targetKeyPath)
	return b.String()
}
