// Copyright (c) 2026 Mauro Silva. All rights reserved.
// SPDX-License-Identifier: LicenseRef-Proprietary

//go:build e2e

// Package e2e drives the five-node topology in deploy/compose.yaml
// (docs/PLAN.md §9). It is the prototype's acceptance gate: every claim the
// architecture makes about routing, policy, credentials, disclosure, and
// telemetry is exercised here against real containers, a real sshd, and a real
// OpenSSH client.
//
// Two deliberate choices shape this harness:
//
//   - Every SSH client invocation runs INSIDE the `user` container, which is on
//     the edge network only. "The target is reachable only through a proxy" is
//     therefore a property of the topology rather than a promise: the node the
//     client runs on has no route to the target at all.
//   - The client is OpenSSH, not a Go SSH library. The acceptance criteria are
//     about what a person at a terminal is told (PLAN §4.3) — banners, channel
//     rejection reasons, exit statuses — so the assertions are made on what a
//     real client actually printed.
//
// The topology's lifecycle belongs to the Makefile (`make e2e`), not to this
// package: keeping them separate is what makes a failing scenario debuggable
// with the containers still up. See deploy/README.md.
//
// Build tag `e2e`: these tests need Docker and cost minutes, so they are out of
// `go test ./...` on purpose.
package e2e

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"
)

// Topology addressing. The compose project name is fixed so `make e2e-down`
// can tear down whatever a failed run left behind.
const (
	composeProject = "hoplock-e2e"
	composeFile    = "deploy/compose.yaml"

	// controlAddr is where the mock Hoplock Control's debug endpoints are
	// published on the host. Only the scenario driver uses it; nothing in the
	// topology reaches Hoplock Control this way.
	controlAddr = "127.0.0.1:18080"

	// deviceDebugAddr is where the fake appliance serves its debug endpoint
	// INSIDE its own container. It is not published: `core` is internal, so a
	// published port would not be reachable from here, and the appliance must
	// not be moved onto a routable network to make one work.
	deviceDebugAddr = "127.0.0.1:8081"

	// SSH listener port inside every proxy container.
	proxyPort = "2222"
)

// Node names, matching deploy/compose.yaml.
const (
	nodeUser     = "user"
	nodeTarget   = "target"
	nodeControl  = "control"
	nodeDevice   = "device"
	proxyDirect  = "proxy-direct"
	proxyNextHop = "proxy-nexthop"
	proxyZone    = "proxy-zone"
)

// Key material inside the containers, generated by deploy/gen-material.sh.
const (
	keyAlice = "/material/user_alice"
	keySvc   = "/material/user_svc"
)

// Timeouts. commandTimeout bounds one client invocation; readyTimeout bounds
// waiting for the topology to settle, which includes a container start, a
// first authorize round trip, and the relay registration handshake.
const (
	commandTimeout = 60 * time.Second
	readyTimeout   = 90 * time.Second
	pollInterval   = 500 * time.Millisecond
)

// repoRoot is the module root, which every compose path is relative to.
var repoRoot string

func TestMain(m *testing.M) {
	root, err := filepath.Abs("../..")
	if err != nil {
		fmt.Fprintf(os.Stderr, "e2e: resolve the repository root: %v\n", err)
		os.Exit(1)
	}
	repoRoot = root
	os.Exit(m.Run())
}

// --- process plumbing --------------------------------------------------------

// result is what one command in the topology produced. A non-zero code is data,
// not a failure: most scenarios here are about a refusal, and the exit status is
// half of what is being asserted.
type result struct {
	stdout string
	stderr string
	code   int
}

// output is everything the invocation printed. Assertions use it rather than
// the streams separately because the proxy writes to the channel's stderr while
// the target's program writes to stdout, and a scenario usually cares that a
// particular sentence reached the user at all.
func (r result) output() string { return r.stdout + r.stderr }

func (r result) String() string {
	return fmt.Sprintf("exit %d\n--- stdout ---\n%s--- stderr ---\n%s", r.code, r.stdout, r.stderr)
}

// runE executes one command on the host, with stdin attached. A non-zero exit
// status is returned in the result rather than as an error: most scenarios here
// are about a refusal, and the exit status is half of what is asserted. The
// error is for the invocation itself failing — a timeout, or no such binary.
//
// It takes no *testing.T so that it can be called from a goroutine, which the
// outage scenario needs: a session has to be running while Hoplock Control is
// stopped out from under it.
func runE(stdin, name string, args ...string) (result, error) {
	ctx, cancel := context.WithTimeout(context.Background(), commandTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = repoRoot
	cmd.Stdin = strings.NewReader(stdin)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	res := result{stdout: stdout.String(), stderr: stderr.String()}
	switch {
	case err == nil:
		return res, nil
	case ctx.Err() != nil:
		return res, fmt.Errorf("%s %v timed out after %s", name, args, commandTimeout)
	default:
		var exitErr *exec.ExitError
		if !errors.As(err, &exitErr) {
			return res, fmt.Errorf("%s %v: %w", name, args, err)
		}
		res.code = exitErr.ExitCode()
		return res, nil
	}
}

// run is runE for the ordinary case, where an invocation that could not run at
// all is a failed test rather than something to inspect.
func run(t *testing.T, stdin string, name string, args ...string) result {
	t.Helper()
	res, err := runE(stdin, name, args...)
	if err != nil {
		t.Fatalf("%v\n%s", err, res)
	}
	return res
}

// compose runs a docker compose subcommand against the topology.
func compose(t *testing.T, args ...string) result {
	t.Helper()
	full := append([]string{"compose", "-p", composeProject, "-f", composeFile}, args...)
	return run(t, "", "docker", full...)
}

// execIn runs a command inside one node and returns what it printed.
func execIn(t *testing.T, node string, argv ...string) result {
	t.Helper()
	return execInWithStdin(t, node, "", argv...)
}

func execInWithStdin(t *testing.T, node, stdin string, argv ...string) result {
	t.Helper()
	return run(t, stdin, "docker", execArgs(node, argv...)...)
}

// execArgs renders the docker arguments that run argv inside one node.
func execArgs(node string, argv ...string) []string {
	return append([]string{"compose", "-p", composeProject, "-f", composeFile, "exec", "-T", node}, argv...)
}

// --- the SSH client ----------------------------------------------------------

// sshBaseArgs are the options every scenario shares.
//
// LogLevel is left at its default on purpose: OpenSSH prints a server's
// USERAUTH_BANNER only at INFO or above, and the banner is where the proxy says
// what went wrong before authentication completes (PLAN §4.3). Quietening the
// client would quietly delete half of what these scenarios assert.
var sshBaseArgs = []string{
	"-o", "StrictHostKeyChecking=no",
	"-o", "UserKnownHostsFile=/dev/null",
	"-o", "GlobalKnownHostsFile=/dev/null",
	"-o", "BatchMode=yes",
	"-o", "IdentitiesOnly=yes",
	"-o", "PreferredAuthentications=publickey",
	"-o", "ConnectTimeout=10",
}

// session describes one SSH client invocation against the topology.
type session struct {
	// proxy is the node the client connects to.
	proxy string
	// key is the private key inside the user container.
	key string
	// login and target are encoded into the SSH username with the proxy's
	// delimiter (D1).
	login, target string
	// opts are extra client options, e.g. "-tt" or a forwarding request.
	opts []string
	// command is the remote command; empty asks for a shell.
	command string
	// stdin is fed to the client.
	stdin string
}

// username renders the D1-encoded login.
func (s session) username() string { return s.login + "#" + s.target }

// argv renders the SSH client invocation this session describes.
func (s session) argv() []string {
	argv := []string{"ssh"}
	argv = append(argv, sshBaseArgs...)
	argv = append(argv, "-i", s.key, "-p", proxyPort, "-l", s.username())
	argv = append(argv, s.opts...)
	argv = append(argv, s.proxy)
	if s.command != "" {
		argv = append(argv, s.command)
	}
	return argv
}

// ssh runs one SSH client invocation inside the user node.
func ssh(t *testing.T, s session) result {
	t.Helper()
	return execInWithStdin(t, nodeUser, s.stdin, s.argv()...)
}

// sshE is ssh without a *testing.T, for the one scenario that has to run a
// session on another goroutine.
func sshE(s session) (result, error) {
	return runE(s.stdin, "docker", execArgs(nodeUser, s.argv()...)...)
}

// sessionIDPattern finds the session id the proxy quotes in its banner. It is
// the support reference PLAN §4.3 promises, and it is also how a scenario can
// name one specific session's records in the audit trail.
var sessionIDPattern = regexp.MustCompile(`Session (sess-[0-9a-f]+)\.`)

// sessionIDOf extracts the session id from what the proxy told the client.
func sessionIDOf(r result) string {
	if m := sessionIDPattern.FindStringSubmatch(r.output()); m != nil {
		return m[1]
	}
	return ""
}

// aliceOn is the interactive user reaching a target through a proxy.
func aliceOn(proxy, target string) session {
	return session{proxy: proxy, key: keyAlice, login: "alice", target: target}
}

// svcOn is the machine account, which the fixtures give the restricted-exec and
// forwarding routes.
func svcOn(proxy, target string) session {
	return session{proxy: proxy, key: keySvc, login: "svc-deploy", target: target}
}

// --- assertions --------------------------------------------------------------

// wantContains fails unless the invocation printed the sentence, showing the
// whole invocation when it did not: a scenario that fails here is usually
// failing several steps earlier.
func wantContains(t *testing.T, r result, what, substr string) {
	t.Helper()
	if !strings.Contains(r.output(), substr) {
		t.Errorf("%s: expected the client to be told %q\n%s", what, substr, r)
	}
}

func wantNotContains(t *testing.T, r result, what, substr string) {
	t.Helper()
	if strings.Contains(r.output(), substr) {
		t.Errorf("%s: the client must not be told %q\n%s", what, substr, r)
	}
}

func wantExit(t *testing.T, r result, what string, code int) {
	t.Helper()
	if r.code != code {
		t.Errorf("%s: exit status %d, want %d\n%s", what, r.code, code, r)
	}
}

func wantFailure(t *testing.T, r result, what string) {
	t.Helper()
	if r.code == 0 {
		t.Errorf("%s: the invocation succeeded; it must not\n%s", what, r)
	}
}

// --- the mock Hoplock Control's debug view -----------------------------------

// debugLogs mirrors cmd/mock-control's GET /debug/logs.
type debugLogs struct {
	Batched  []logRecord `json:"batched"`
	Priority []logRecord `json:"priority"`
}

// logRecord is the subset of control.LogRecord the scenarios assert on.
type logRecord struct {
	SessionID  string            `json:"session_id"`
	Kind       string            `json:"kind"`
	Severity   string            `json:"severity"`
	Message    string            `json:"message"`
	Login      string            `json:"login"`
	Target     string            `json:"target"`
	Attributes map[string]string `json:"attributes"`
}

// mentions reports whether the record names the text anywhere a scenario would
// look — its message or any structured attribute.
func (r logRecord) mentions(text string) bool {
	if strings.Contains(r.Message, text) {
		return true
	}
	for _, v := range r.Attributes {
		if strings.Contains(v, text) {
			return true
		}
	}
	return false
}

// fetchLogs reads what Hoplock Control has ingested so far.
func fetchLogs(t *testing.T) debugLogs {
	t.Helper()
	logs, err := tryFetchLogs()
	if err != nil {
		t.Fatalf("read the ingested logs: %v", err)
	}
	return logs
}

func tryFetchLogs() (debugLogs, error) {
	var logs debugLogs
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, "http://"+controlAddr+"/debug/logs", nil)
	if err != nil {
		return logs, err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return logs, err
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return logs, fmt.Errorf("GET /debug/logs: %s", resp.Status)
	}
	return logs, json.NewDecoder(resp.Body).Decode(&logs)
}

// deviceAccounts reads the fake appliance's administrator table.
//
// It is the device half of what testNoEphemeralLeak reads off the target with
// `getent passwd`. An appliance has no account database to read, so the fixture
// publishes one — driving the CLI instead would mean asserting on the proxy's
// cleanup through the same commands the proxy used to do it.
func deviceAccounts(t *testing.T) []string {
	t.Helper()
	accounts, err := tryDeviceAccounts()
	if err != nil {
		t.Fatalf("read the device's administrator table: %v", err)
	}
	return accounts
}

func tryDeviceAccounts() ([]string, error) {
	// Read from inside the appliance's own container rather than over a
	// published port: see deviceDebugAddr, and deploy/compose.yaml.
	r, err := runE("", "docker", execArgs(nodeDevice, "hoplock-fake-device", "-dump", deviceDebugAddr)...)
	if err != nil {
		return nil, err
	}
	if r.code != 0 {
		return nil, fmt.Errorf("read the appliance's administrator table: %v", r)
	}
	var body struct {
		Accounts []string `json:"accounts"`
	}
	if err := json.Unmarshal([]byte(r.stdout), &body); err != nil {
		return nil, fmt.Errorf("decode the appliance's administrator table from %q: %w", r.stdout, err)
	}
	return body.Accounts, nil
}

// --- waiting -----------------------------------------------------------------

// waitFor polls until cond holds, and fails with what the caller was waiting
// for rather than with a timeout nobody can interpret.
func waitFor(t *testing.T, what string, cond func() bool) {
	t.Helper()
	deadline := time.Now().Add(readyTimeout)
	for time.Now().Before(deadline) {
		if cond() {
			return
		}
		time.Sleep(pollInterval)
	}
	t.Fatalf("timed out after %s waiting for %s", readyTimeout, what)
}

// requireTopology fails the whole run, early and legibly, unless the topology
// is up and every node has settled. `make e2e` brings it up; a bare `go test`
// against a torn-down topology would otherwise fail one scenario at a time with
// a different error each.
func requireTopology(t *testing.T) {
	t.Helper()

	if r := compose(t, "ps", "--status", "running", "--format", "{{.Service}}"); r.code != 0 ||
		!strings.Contains(r.stdout, proxyDirect) {
		t.Fatalf("the topology is not running — start it with `make e2e-up`\n%s", r)
	}

	waitFor(t, "Hoplock Control to answer", func() bool {
		_, err := tryFetchLogs()
		return err == nil
	})
	waitFor(t, "the target's sshd through proxy-direct", func() bool {
		s := aliceOn(proxyDirect, "host.company.com")
		s.command = "/bin/true"
		return ssh(t, s).code == 0
	})
	waitFor(t, "the appliance's CLI to answer", func() bool {
		_, err := tryDeviceAccounts()
		return err == nil
	})
	// The relay registration is the one piece of the topology with no
	// synchronous readiness signal: proxy-zone dials out and retries. Waiting
	// on it here is also what keeps the "no live registration" scenario honest
	// — that one must fail because the registration is absent, never because
	// the topology had not finished starting.
	waitFor(t, "proxy-zone's relay registration with proxy-nexthop", func() bool {
		s := aliceOn(proxyNextHop, "zone.company.com")
		s.command = "/bin/true"
		return ssh(t, s).code == 0
	})
}
